nats:
  url: "{{ cookiecutter.nats_url }}"
  user: "{{ cookiecutter.nats_user }}"
  password: "{{ cookiecutter.nats_password }}"
client:
  id: "{{ cookiecutter.client_id }}"
llm:
  cloud_api_key: ""  # Set via environment variable LLAMA_CLOUD_API_KEY
chroma:
  path: "{{ cookiecutter.chroma_db_path }}" 